### PR TITLE
Use Objective-C 2.0 subscripting

### PR DESCRIPTION
**Pull request by dlo**

### CODE REVIEW

**Comment by thankmelater23** [comment]
will this fix the issues with RETPickerItem while using swift?  I'm new to using github and cocoapods.  I see you changed the code where I was getting errors in my project.  I updated my pod file, but I dont see any of the changes that you made.  Do I have to wait till he merges your changes into the master?  Thanks in advance!

**Comment by dlo** [comment]
Good question...uncertain if this would fix any Swift related issues but honestly would be surprised if it did. We'll need to wait until this is merged until you can test with a pod update (if you want to do the more manual approach, I believe you can point to my fork in your Podfile--there is some syntax for that but can't remember it off the top of my head).

**Comment by thankmelater23** [comment]
Thanks dude ill go ahead and research it now.  Hopefully he merges it also.

**Comment by XBeg9** [comment]
@dlo nice.

**Pull request merged**
