### PR TITLE
Removed/renamed duplicated class properties to fix warnings.

### PR DESCRIPTION
**Pull request by xingheng**
RT, for fixing all the suppress warnings.

### CODE REVIEW

**Comment by xingheng** [comment]
Ping...

**Comment by XBeg9** [comment]
Pong. Please `rebase` your branch onto latest `master`. Thanks @xingheng

**Comment by xingheng** [comment]
Ping... @XBeg9

**Comment by XBeg9** [comment]
@xingheng thanks

**Pull request merged**
